import {
  mdiAccount, mdiAlert, mdiAlertCircle, mdiAlertCircleOutline,
  mdiArrowDown, mdiArrowLeft, mdiArrowUp,
  mdiAutoFix,
  mdiBrain,
  mdiBriefcaseOutline, mdiBriefcaseSearch,
  mdiCached, mdiCalendar, mdiChartLine,
  mdiCheck, mdiCheckboxBlankOutline, mdiCheckboxMarked, mdiCheckCircle,
  mdiChevronDown, mdiChevronLeft, mdiChevronRight, mdiChevronUp,
  mdiCircle, mdiClose, mdiCloseCircle, mdiCloudUpload, mdiCodeJson,
  mdiCompareHorizontal,
  mdiDelete, mdiDeleteCircle, mdiDeleteOutline, mdiDownload, mdiDrag,
  mdiEyedropper,
  mdiFileCheck, mdiFileDocumentCheck, mdiFileDocumentEdit, mdiFileDocumentOutline,
  mdiFileEdit, mdiFilePdfBox,
  mdiFormatBold, mdiFormatClear, mdiFormatItalic,
  mdiFormatListBulleted, mdiFormatListNumbered,
  mdiInformation, mdiInformationOutline,
  mdiKeyboardOutline,
  mdiLightningBolt, mdiLightningBoltOutline,
  mdiLink, mdiLoading, mdiLockOutline,
  mdiMenu, mdiMenuDown, mdiMinus, mdiMinusBox,
  mdiPageFirst, mdiPageLast, mdiPaperclip, mdiPencil, mdiPlus,
  mdiRadioboxBlank, mdiRadioboxMarked, mdiRefresh,
  mdiShieldCheck, mdiShieldLock, mdiShieldLockOutline,
  mdiStar, mdiStarHalfFull, mdiStarOutline,
  mdiSwapHorizontal,
  mdiTextBoxOutline,
  mdiUndo, mdiUnfoldMoreHorizontal, mdiUpload, mdiUploadMultiple,
  mdiViewList,
} from '@mdi/js'

// Maps mdi-xxx class names → SVG path strings (used in <v-icon>mdi-xxx</v-icon>)
export const mdiIconMap: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-alert': mdiAlert,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-auto-fix': mdiAutoFix,
  'mdi-brain': mdiBrain,
  'mdi-briefcase-outline': mdiBriefcaseOutline,
  'mdi-briefcase-search': mdiBriefcaseSearch,
  'mdi-chart-line': mdiChartLine,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-close': mdiClose,
  'mdi-cloud-upload': mdiCloudUpload,
  'mdi-code-json': mdiCodeJson,
  'mdi-compare-horizontal': mdiCompareHorizontal,
  'mdi-delete': mdiDelete,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-download': mdiDownload,
  'mdi-drag': mdiDrag,
  'mdi-file-check': mdiFileCheck,
  'mdi-file-document-check': mdiFileDocumentCheck,
  'mdi-file-document-edit': mdiFileDocumentEdit,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-file-edit': mdiFileEdit,
  'mdi-file-pdf-box': mdiFilePdfBox,
  'mdi-format-bold': mdiFormatBold,
  'mdi-format-clear': mdiFormatClear,
  'mdi-format-italic': mdiFormatItalic,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-format-list-numbered': mdiFormatListNumbered,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-keyboard-outline': mdiKeyboardOutline,
  'mdi-lightning-bolt': mdiLightningBolt,
  'mdi-lightning-bolt-outline': mdiLightningBoltOutline,
  'mdi-link': mdiLink,
  'mdi-loading': mdiLoading,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-shield-check': mdiShieldCheck,
  'mdi-shield-lock': mdiShieldLock,
  'mdi-shield-lock-outline': mdiShieldLockOutline,
  'mdi-swap-horizontal': mdiSwapHorizontal,
  'mdi-text-box-outline': mdiTextBoxOutline,
  'mdi-undo': mdiUndo,
  'mdi-upload': mdiUpload,
  'mdi-upload-multiple': mdiUploadMultiple,
  'mdi-view-list': mdiViewList,
}

// Vuetify's internal icon aliases (used by v-expansion-panel, v-select, etc.)
export const vuetifyAliases = {
  collapse: mdiChevronUp,
  complete: mdiCheck,
  cancel: mdiCloseCircle,
  close: mdiClose,
  delete: mdiDeleteCircle,
  clear: mdiClose,
  success: mdiCheckCircle,
  info: mdiInformation,
  warning: mdiAlert,
  error: mdiAlertCircle,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: mdiCheckboxMarked,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBox,
  delimiter: mdiCircle,
  sortAsc: mdiArrowUp,
  sortDesc: mdiArrowDown,
  expand: mdiChevronDown,
  menu: mdiMenu,
  subgroup: mdiMenuDown,
  dropdown: mdiMenuDown,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiCached,
  first: mdiPageFirst,
  last: mdiPageLast,
  unfold: mdiUnfoldMoreHorizontal,
  file: mdiPaperclip,
  plus: mdiPlus,
  minus: mdiMinus,
  calendar: mdiCalendar,
  eyeDropper: mdiEyedropper,
  treeviewCollapse: mdiChevronDown,
  treeviewExpand: mdiChevronRight,
}
