<template>
  <div 
    v-if="show" 
    class="modal-overlay" 
    @click="$emit('close')"
    role="dialog"
    aria-modal="true"
    aria-labelledby="info-modal-title"
    aria-describedby="info-modal-description"
  >
    <div class="modal-content" @click.stop ref="modalRef">
      <div class="modal-header">
        <div class="header-content">
          <div class="header-left">
            <Icon icon="material-symbols:info" style="font-size: 20px; margin-right: 8px;" aria-hidden="true" />
            <h3 id="info-modal-title">Using AI to Generate a Resume</h3>
          </div>
          <button 
            class="modal-close" 
            @click="$emit('close')"
            aria-label="Close information dialog"
          >
            <Icon icon="material-symbols:close" style="font-size: 20px;" aria-hidden="true" />
          </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="info-content" id="info-modal-description">
          <p>This application now includes a smart import feature that can handle file uploads, resume text, and JSON data. For more advanced customization, you can also use external AI tools.</p>
          
          <ol class="step-list" role="list">
            <li class="step-item">
              <span class="step-number" aria-hidden="true">1</span>
              <div class="step-content">
                <strong>File Upload:</strong> Drag and drop or browse to upload resume files (.txt, .rtf, .doc, .docx, .pdf). The system will extract text and process it automatically.
              </div>
            </li>
            
            <li class="step-item">
              <span class="step-number" aria-hidden="true">2</span>
              <div class="step-content">
                <strong>Text Import:</strong> Use the "Import Resume" button to paste any resume text directly. The system will automatically convert it to the correct format.
              </div>
            </li>
            
            <li class="step-item">
              <span class="step-number" aria-hidden="true">3</span>
              <div class="step-content">
                <strong>JSON Import:</strong> If you have valid JSON resume data (exported from this app or generated by AI), paste it directly in the Import Resume field. It will be detected and imported instantly.
              </div>
            </li>
            
            <li class="step-item">
              <span class="step-number" aria-hidden="true">4</span>
              <div class="step-content">
                <strong>External AI (Advanced):</strong> Export your current resume as JSON, provide it to ChatGPT/Claude/Gemini along with your content, ask for a new JSON structure, then import the result.
              </div>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, nextTick, onMounted, onUnmounted } from 'vue'
import { Icon } from '@iconify/vue'
import { useFocusTrap } from '~/composables/useFocusTrap'
import { useBodyScrollLock } from '~/composables/useBodyScrollLock'

const props = defineProps({
  show: {
    type: Boolean,
    required: true
  }
})

const emit = defineEmits(['close'])

const modalRef = ref(null)
const { trapFocus, releaseFocus } = useFocusTrap()
const { lockScroll, unlockScroll } = useBodyScrollLock()

// Focus trap and scroll lock
watch(() => props.show, (isOpen) => {
  if (isOpen) {
    lockScroll()
    nextTick(() => {
      if (modalRef.value) {
        trapFocus(modalRef.value)
      }
    })
  } else {
    unlockScroll()
    releaseFocus()
  }
})

// Escape key handler
onMounted(() => {
  const handleEscape = (e) => {
    if (e.key === 'Escape' && props.show) {
      emit('close')
    }
  }
  document.addEventListener('keydown', handleEscape)
  
  onUnmounted(() => {
    document.removeEventListener('keydown', handleEscape)
    unlockScroll()
    releaseFocus()
  })
})
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2000;
}

.modal-content {
  background: white;
  border-radius: 12px;
  width: 90%;
  max-width: 600px;
  max-height: 80vh;
  overflow: hidden;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
  border: 1px solid #e2e8f0;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24px;
  border-bottom: 1px solid #e2e8f0;
  background: #f8fafc;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1e293b;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 0;
}

.header-left {
  display: flex;
  align-items: center;
}

.modal-close {
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  color: #475569; /* 7.6:1 contrast - AAA compliant */
  padding: 6px;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  transition: all 0.2s ease;
}

.modal-close:hover {
  background: #f1f5f9;
  color: #1e293b; /* Higher contrast on hover */
}

.modal-body {
  padding: 24px;
  overflow-y: auto;
  max-height: calc(80vh - 80px);
}

.info-content {
  line-height: 1.6;
}

.info-content p {
  margin: 0 0 20px 0;
  color: #475569;
}

.step-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
  list-style: none;
  padding: 0;
  margin: 0;
}

.step-item {
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.step-number {
  background: #3b82f6;
  color: white;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
}

.step-content {
  color: #475569;
  line-height: 1.5;
}

.step-content strong {
  color: #1e293b;
}
</style>

