<template>
  <v-dialog
    :model-value="show"
    max-width="560"
    scrollable
    @update:model-value="val => !val && $emit('close')"
  >
    <v-card rounded="lg">
      <v-toolbar color="surface-variant" density="comfortable" flat>
        <v-icon class="ml-3 mr-1" color="primary">mdi-information</v-icon>
        <v-toolbar-title class="text-subtitle-1 font-weight-semibold" id="info-modal-title">
          Using AI to Generate a Resume
        </v-toolbar-title>
        <template #append>
          <v-btn icon variant="text" aria-label="Close information dialog" @click="$emit('close')">
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </template>
      </v-toolbar>
      <v-divider />
      <v-card-text class="pa-6" id="info-modal-description">
        <p class="text-body-2 text-medium-emphasis mb-5 mt-0">
          This application includes a smart import feature that handles file uploads, resume text, and JSON data.
          For advanced customization, you can also use external AI tools.
        </p>
        <div v-for="(step, i) in steps" :key="i" class="d-flex align-start mb-4">
          <v-avatar size="24" color="primary" class="flex-shrink-0 mr-3 mt-1" aria-hidden="true">
            <span class="text-caption font-weight-bold text-white">{{ i + 1 }}</span>
          </v-avatar>
          <div class="text-body-2 text-medium-emphasis">
            <strong class="text-on-surface">{{ step.title }}:</strong> {{ step.text }}
          </div>
        </div>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script setup>
defineProps({ show: { type: Boolean, required: true } })
defineEmits(['close'])

const steps = [
  { title: 'File Upload', text: 'Drag and drop or browse to upload resume files (.txt, .rtf, .doc, .docx, .pdf). The system extracts text and processes it automatically.' },
  { title: 'Text Import', text: 'Use the "Import Resume" button to paste any resume text directly. The system converts it to the correct format automatically.' },
  { title: 'JSON Import', text: 'Paste valid JSON resume data (exported from this app or generated by AI) and it will be detected and imported instantly.' },
  { title: 'External AI (Advanced)', text: 'Export your current resume as JSON, provide it to ChatGPT/Claude/Gemini along with your content, ask for a new JSON structure, then import the result.' },
]
</script>
