<template>
  <div v-if="show" class="modal-overlay" @click="$emit('close')">
    <div class="modal-content" @click.stop>
      <div class="modal-header">
        <div class="header-content">
          <div class="header-left">
            <Icon icon="material-symbols:info" style="font-size: 20px; margin-right: 8px;" />
            <h3>Using AI to Generate a Resume</h3>
          </div>
          <button class="modal-close" @click="$emit('close')">
            <Icon icon="material-symbols:close" style="font-size: 20px;" />
          </button>
        </div>
      </div>
      <div class="modal-body">
        <div class="info-content">
          <p>This application now includes a smart import feature that can handle file uploads, resume text, and JSON data. For more advanced customization, you can also use external AI tools.</p>
          
          <div class="step-list">
            <div class="step-item">
              <span class="step-number">1</span>
              <div class="step-content">
                <strong>File Upload:</strong> Drag and drop or browse to upload resume files (.txt, .rtf, .doc, .docx, .pdf). The system will extract text and process it automatically.
              </div>
            </div>
            
            <div class="step-item">
              <span class="step-number">2</span>
              <div class="step-content">
                <strong>Text Import:</strong> Use the "Import Resume" button to paste any resume text directly. The system will automatically convert it to the correct format.
              </div>
            </div>
            
            <div class="step-item">
              <span class="step-number">3</span>
              <div class="step-content">
                <strong>JSON Import:</strong> If you have valid JSON resume data (exported from this app or generated by AI), paste it directly in the Import Resume field. It will be detected and imported instantly.
              </div>
            </div>
            
            <div class="step-item">
              <span class="step-number">4</span>
              <div class="step-content">
                <strong>External AI (Advanced):</strong> Export your current resume as JSON, provide it to ChatGPT/Claude/Gemini along with your content, ask for a new JSON structure, then import the result.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { Icon } from '@iconify/vue'

defineProps({
  show: {
    type: Boolean,
    required: true
  }
})

defineEmits(['close'])
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 2000;
}

.modal-content {
  background: white;
  border-radius: 12px;
  width: 90%;
  max-width: 600px;
  max-height: 80vh;
  overflow: hidden;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
  border: 1px solid #e2e8f0;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24px;
  border-bottom: 1px solid #e2e8f0;
  background: #f8fafc;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1e293b;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 0;
}

.header-left {
  display: flex;
  align-items: center;
}

.modal-close {
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  color: #64748b;
  padding: 6px;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  transition: all 0.2s ease;
}

.modal-close:hover {
  background: #f1f5f9;
  color: #334155;
}

.modal-body {
  padding: 24px;
  overflow-y: auto;
  max-height: calc(80vh - 80px);
}

.info-content {
  line-height: 1.6;
}

.info-content p {
  margin: 0 0 20px 0;
  color: #475569;
}

.step-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.step-item {
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.step-number {
  background: #3b82f6;
  color: white;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
}

.step-content {
  color: #475569;
  line-height: 1.5;
}

.step-content strong {
  color: #1e293b;
}
</style>

